// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTZ29TPmrMMg6Uc0mymCup909I7SoS28',
    appId: '1:940127221325:web:ecabf4f5a12a27d11b8e04',
    messagingSenderId: '940127221325',
    projectId: 'chat-app-b83d6',
    authDomain: 'chat-app-b83d6.firebaseapp.com',
    storageBucket: 'chat-app-b83d6.appspot.com',
    measurementId: 'G-6X0FFLBGCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF2-2q_KvrzmIx3cSLO_o2KtHj3BNswic',
    appId: '1:940127221325:android:7c258f80193785521b8e04',
    messagingSenderId: '940127221325',
    projectId: 'chat-app-b83d6',
    storageBucket: 'chat-app-b83d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-li3W11o7N0H4Ssmk-2vXmUsbonNTN8',
    appId: '1:940127221325:ios:1161d0bf9f846fbb1b8e04',
    messagingSenderId: '940127221325',
    projectId: 'chat-app-b83d6',
    storageBucket: 'chat-app-b83d6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-li3W11o7N0H4Ssmk-2vXmUsbonNTN8',
    appId: '1:940127221325:ios:1282879dca4fc2261b8e04',
    messagingSenderId: '940127221325',
    projectId: 'chat-app-b83d6',
    storageBucket: 'chat-app-b83d6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
